### ISSUE TITLE
Archive broken (needs cache switching off)

### ISSUE THREAD

**Issue by JimKillock** [splittingred/MODxSampleSite#1]
The archive function doesn't work by default after a page refresh.

It may need &cache=`0` adding to the archive page getPage call?

[[!getPage?
  &element=`getArchives`
  &elementClass=`modSnippet`
  &tpl=`blogPost`
  &hideContainers=`1`
  &showHidden=`1`
  &pageVarKey=`page`
  &parents=`2`
  &includeTVs=`1`
  &toPlaceholder=`archives`
  &limit=`10`
]]

**Comment by splittingred** [comment]
Fixed archives display with caching: Closed by 490d2cca4bb05d550540ac1365c457560a30b957
Fixed bugs with contact form, request acct form: Closed by 490d2cca4bb05d550540ac1365c457560a30b957 Closed by 490d2cca4bb05d550540ac1365c457560a30b957
Fixed bug with logout link: Closed by 490d2cca4bb05d550540ac1365c457560a30b957
