### ISSUE TITLE
Request account page / form: broken captcha

### ISSUE THREAD

**Issue by JimKillock** [splittingred/MODxSampleSite#3]
By default, the install's request account form has a broken captcha form. The missing image href points to:

/manager/includes/veriword.php

**Comment by splittingred** [comment]
Fixed archives display with caching: Closed by 490d2cca4bb05d550540ac1365c457560a30b957
Fixed bugs with contact form, request acct form: Closed by 490d2cca4bb05d550540ac1365c457560a30b957 Closed by 490d2cca4bb05d550540ac1365c457560a30b957
Fixed bug with logout link: Closed by 490d2cca4bb05d550540ac1365c457560a30b957
