### ISSUE TITLE
Problems with forms (sending blank emails) / missing form template

### ISSUE THREAD

**Issue by JimKillock** [splittingred/MODxSampleSite#4]
The contact form call asks: &emailTpl=`ContactFormReport` which is not included with the default sample site content

**Comment by splittingred** [comment]
Fixed contact form email report and subject: Closed by fdac7ae8b7912d32f2c73ffe7b05ea88e86adbc4 Closed by fdac7ae8b7912d32f2c73ffe7b05ea88e86adbc4
