### ISSUE TITLE
Problem with formit contact form

### ISSUE THREAD

**Issue by JimKillock** [splittingred/MODxSampleSite#5]
This part of the contact form;
         <label for="cfMessage">Message: 
            <span class="invalidValue">[[+fi.error.message]]</span>
        <textarea id="cfMessage" cols="20" rows="4" name="message:required"></textarea>
        </label>

Looks like it has missing fields compared to the formit example:
    <label for="text">  
        Message:  
        <span class="error">[[+fi.error.text]]</span>  
    </label>  
    <textarea name="text:required:stripTags" id="text" cols="55" rows="7" value="[[+fi.text]]">[[+fi.text]]</textarea>

**Comment by splittingred** [comment]
Fixed archives display with caching: Closed by 490d2cca4bb05d550540ac1365c457560a30b957
Fixed bugs with contact form, request acct form: Closed by 490d2cca4bb05d550540ac1365c457560a30b957 Closed by 490d2cca4bb05d550540ac1365c457560a30b957
Fixed bug with logout link: Closed by 490d2cca4bb05d550540ac1365c457560a30b957
