### ISSUE TITLE
Contact form creates emails missing subject line

### ISSUE THREAD

**Issue by JimKillock** [splittingred/MODxSampleSite#6]
No subject line is fed through to the emails generated by the form.
        <label for="cfRegarding">Regarding:
            <span class="invalidValue">[[+fi.error.regarding]]</span>
        </label>  
        <select id="cfRegarding" name="subject:required">
            <option value="General Inquiries">General Inquiries</option>
            <option value="Press">Press or Interview Request</option>
            <option value="Partnering">Partnering Opportunities</option>
        </select>

**Comment by splittingred** [comment]
Fixed contact form email report and subject: Closed by fdac7ae8b7912d32f2c73ffe7b05ea88e86adbc4 Closed by fdac7ae8b7912d32f2c73ffe7b05ea88e86adbc4
