### ISSUE TITLE
Logout link doesn't work

### ISSUE THREAD

**Issue by odeclas** [splittingred/MODxSampleSite#7]
I think the param needs to be &service=`logout` instead of &logout=`true`

**Comment by splittingred** [comment]
Fixed archives display with caching: Closed by 490d2cca4bb05d550540ac1365c457560a30b957
Fixed bugs with contact form, request acct form: Closed by 490d2cca4bb05d550540ac1365c457560a30b957 Closed by 490d2cca4bb05d550540ac1365c457560a30b957
Fixed bug with logout link: Closed by 490d2cca4bb05d550540ac1365c457560a30b957
